version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: taman-kehati-db
    environment:
      POSTGRES_DB: taman_kehati
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: taman-kehati-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/taman_kehati
      - ASYNC_DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/taman_kehati
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata: