version: '3.8'

services:
  api:
    build: .
    container_name: taman-kehati-api
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ASYNC_DATABASE_URL=${ASYNC_DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ENV=${ENV:-production}
      - DEBUG=${DEBUG:-False}
    volumes:
      - ./uploads:/app/uploads
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000